# tests/test_memory/test_summarized_memory.py
import pytest
import asyncio
import json
from unittest.mock import AsyncMock, patch

from stream_agent.memory.summarized_memory import SummarizedMemoryManager
from stream_agent.memory.redis_plugin import RedisMemoryPlugin

@pytest.mark.asyncio
@patch("stream_agent.memory.redis_plugin.redis.from_url")
@patch("stream_agent.memory.summarized_memory.AsyncLLMEngine.generate_text")
async def test_summarized_memory_flow(mock_generate_text, mock_redis_from_url):
    """
    Test point：
    1. Normal writing does not block the main thread.
    2. An asynchronous LLM summary is triggered after the threshold is reached.
    3. When obtaining the history, the summary can be spliced into the System Prompt correctly.
    4. Session-level Lock isolation works normally.
    """
    # ==========================
    # 1. Simulate Redis client and return value
    # ==========================
    mock_redis = AsyncMock()
    mock_redis_from_url.return_value = mock_redis
    
    # Summary of simulation of large model generation
    mock_generate_text.return_value = "Condensed memory summary generated by the test: Users want high concurrency deployment。"
    
    # Simulate Redis to obtain history (assuming that there are 8 messages in the current cache, which just reaches the threshold)
    mock_history_data = [
        json.dumps({"role": "user", "content": f"The {i} round of dialogue"}) for i in range(8)
    ]
    mock_redis.lrange.return_value = mock_history_data
    
    # Simulate Redis to get an existing summary
    mock_redis.get.return_value = None 

    # ==========================
    # 2. Initialize the memory manager
    # ==========================
    session_id = "test_session_isolated_001"
    memory_manager = SummarizedMemoryManager(
        agent_name="test_agent",
        redis_url="redis://fake_url",
        l1_max_len=10,
        summarize_threshold=8 # set threshold 8
    )

    # ==========================
    # 3. Test save message and bypass summary trigger
    # ==========================
    # This step should be returned quickly, and a _safe_async_summarize task will be suspended in the background
    await memory_manager.save_message(session_id, "user", "A new message that triggers the summary")
    
    # Wait for the background task in the event loop to be executed (simulate the bypass waiting in real operation)
    await asyncio.sleep(0.1) 
    
    # Assert that LLM was called once (because there are more than 8)
    mock_generate_text.assert_called_once()
    
    # The summary generated by the assertion is written back to Redis
    summary_key = f"memory:summary:{session_id}"
    mock_redis.set.assert_any_call(summary_key, "Condensed memory summary generated by the test: Users want high concurrency deployment。", ex=2592000)
    
    # Assert that the L1 cache is safely trimmed (keep the most recent 4 and trim off the old ones)
    history_key = f"memory:session:{session_id}"
    mock_redis.ltrim.assert_any_call(history_key, -4, -1)

    # ==========================
    # 4. Automatically inject the summary when the test is read
    # ==========================
    # Change Redis.get The return value of get, the simulation already has a summary
    mock_redis.get.return_value = "Condensed memory summary generated by the test: Users want high concurrency deployment。"
    
    # Get history
    history = await memory_manager.get_history(session_id)
    
    # Assert that the first message was forcibly injected into System Prompt, which contains our compressed summary
    assert len(history) > 0
    assert history[0]["role"] == "system"
    assert "Condensed memory summary generated by the test" in history[0]["content"]
    assert "Please combine the above summary to understand the user's follow-up request" in history[0]["content"]

@pytest.mark.asyncio
async def test_session_isolation_locks():
    """When verifying that multiple sessions trigger the digest concurrently, the lock is strictly physically isolated"""
    manager = SummarizedMemoryManager(agent_name="test")
    
    lock1 = manager._get_session_lock("session_A")
    lock2 = manager._get_session_lock("session_B")
    lock3 = manager._get_session_lock("session_A")
    
    # Different sessions must be different lock objects
    assert lock1 is not lock2
    # The same lock must be reused for the same session
    assert lock1 is lock3